### ISSUE TITLE
How to upload video to Vimeo from Android app using this Library?

### ISSUE THREAD

**Issue by coneits** [vimeo/vimeo-deeplink-android#17]
Hello.

I would like to upload video to vimeo from my android app.
Can I upload video from my android app using your github repository?
Or is there any other published github source code that can upload video?

Thanks,
Look forward to hearing from you.

Best Regards.

**Comment by kevinzetterstrom** [comment]
Hi @coneits 
This library doesn't specifically provide functionality to upload, but provides a helper method to open the official Vimeo Android application to begin the upload process.

If you integrate this library (follow the [ReadMe](https://github.com/vimeo/vimeo-deeplink-android#getting-started)) into your application, you can use the following method:

```VimeoDeeplink.showUpload(Context context)```

The method will return true if the user has the Vimeo Android app installed and that version of the app can handle uploading. The method will return false otherwise.

As of this writing, there are no official Vimeo Android libraries that allow for uploading videos, however, we hope to release one in the future. For now, if you would like to upload in a manner other than using this deep link approach, then you will have to follow the [API documentation](https://developer.vimeo.com/api/upload/videos) on uploading.

**Comment by AbhijitKurane** [comment]
Hey kevinzetterstrom, 
I have same question. Do we have any library by Vimeo using which I can upload a video on vimeo and stream the same. If there is no any official library are we planning to have it in future?
We even checked the below link. But didn't find any success.
https://github.com/vimeo/vimeo-networking-java/tree/v2.0.0/example-java-android/src/main
Waiting for your response.

**Comment by kevinzetterstrom** [comment]
Hi @AbhijitKurane, 
There is currently no library by Vimeo for Android that simplifies the upload process at this time. We also do not have a library that simply allows for viewing videos. For both of these cases, you would have to build your own solutions. You may find it helpful to use our [networking](https://github.com/vimeo/vimeo-networking-java) library, but by no means will that solve the problem that you face on its own.

We would love to build these ourselves in order to facilitate integration into non-Vimeo applications, and both are on our radar, but neither have any time frame associated with them.

Kevin

**Comment by kevinzetterstrom** [comment]
I am closing this issue since it is a question that has now been answered. Good luck with the integrations 😄

**Comment by AbhijitKurane** [comment]
Thanks for the prompt reply @kevinzetterstrom . We will like to have it in coming days.
Thank you again.

**Comment by soonsam123** [comment]
Is there any new information about uploading videos using this library? or any preview about this feature?

**Comment by brentwatson** [comment]
@soonsam123 our Vimeo mobile app now supports Android's standard `SEND` intent for all `video/*` mime types. This will open the application to our upload screen for the selected Video. 

You can either use the regular system chooser and share your video file:

```kotlin
val shareIntent: Intent = Intent().apply {
    action = Intent.ACTION_SEND
    putExtra(Intent.EXTRA_STREAM, uriToVideo)
    type = "video/(type)"
}
startActivity(Intent.createChooser(shareIntent, "Share Video"))
```

or you can specify the Vimeo app package name (`com.vimeo.android.videoapp`) to only allow the video to be sent to the Vimeo app.

```kotlin
...
shareIntent.setPackage("com.vimeo.android.videoapp");
startActivity(Intent.createChooser(share, "Share Image"));
```
